config/routes.rb
GeneralExpense::Application.routes.draw do
  resources :clients

  resources :mileage_segments

  resources :travel_expenses

  resources :travels

  resources :vehicle_expenses

  resources :vehicles

  resources :me_exps

  resources :gen_exps

  resources :expenses

   root :to => 'gen_exps#index'

end

app/models/travel.rb
class Travel < ActiveRecord::Base
  attr_accessible :destination, :end_date, :start_date, :purpose

  #Associations
  has_many :travel_expenses

  #Validations
  validates_presence_of :destination, :end_date, :start_date, :purpose
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
 

  # GET /travels
  # GET /travels.json
  def index
    @travels = Travel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @travels }
    end
  end

  # GET /travels/1
  # GET /travels/1.json
  def show
    @travel = Travel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @travel }
    end
  end

  # GET /travels/new
  # GET /travels/new.json
  def new
    @travel = Travel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @travel }
    end
  end

  # GET /travels/1/edit
  def edit
    @travel = Travel.find(params[:id])
  end

  # POST /travels
  # POST /travels.json
  def create
    @travel = Travel.new(params[:travel])

    respond_to do |format|
      if @travel.save
        format.html { redirect_to @travel, notice: 'Travel was successfully created.' }
        format.json { render json: @travel, status: :created, location: @travel }
      else
        format.html { render action: "new" }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /travels/1
  # PUT /travels/1.json
  def update
    @travel = Travel.find(params[:id])

    respond_to do |format|
      if @travel.update_attributes(params[:travel])
        format.html { redirect_to @travel, notice: 'Travel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travels/1
  # DELETE /travels/1.json
  def destroy
    @travel = Travel.find(params[:id])
    @travel.destroy

    respond_to do |format|
      format.html { redirect_to travels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/travels/_form.html.erb
<%= simple_form_for(@travel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :destination %>
    <%= f.input :purpose %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Add Trip" %>
  </div>
<% end %>

app/views/travels/edit.html.erb
<h1>Trips</h1>

<%= render 'form' %>

<%= link_to 'Show', @travel %> |
<%= link_to 'Back', travels_path %>

app/views/travels/index.html.erb
<h1>Trips</h1>

<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Destination</th>
    <th>Purpose</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @travels.each do |travel| %>
  <tr>
    <td><%= travel.start_date %></td>
    <td><%= travel.end_date %></td>
    <td><%= travel.destination %></td>
    <td><%= travel.purpose %></td>
    <td><%= link_to 'Show', travel %></td>
    <td><%= link_to 'Edit', edit_travel_path(travel) %></td>
    <td><%= link_to 'Destroy', travel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Trip', new_travel_path %> | <%= link_to 'Travel Expenses', travel_expenses_path %> 

app/views/travels/new.html.erb
<h1>Trips</h1>

<%= render 'form' %>

<%= link_to 'Back', travels_path %>

app/views/travels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start Date:</b>
  <%= @travel.start_date %>
</p>

<p>
  <b>End Date:</b>
  <%= @travel.end_date %>
</p>

<p>
  <b>Destination:</b>
  <%= @travel.destination %>
</p>

<p>
	<b>Purpose</b>
	<%= @travel.purpose %>
</p>


<%= link_to 'Edit', edit_travel_path(@travel) %> |
<%= link_to 'Trips', travels_path %> | <%= link_to 'New Expense', new_travel_expense_path %>