config/routes.rb
GeneralExpense::Application.routes.draw do
  resources :clients

  resources :mileage_segments

  resources :travel_expenses

  resources :travels

  resources :vehicle_expenses

  resources :vehicles

  resources :me_exps

  resources :gen_exps

  resources :expenses

   root :to => 'gen_exps#index'

end

app/models/mileage_segment.rb
class MileageSegment < ActiveRecord::Base
  attr_accessible :date, :destination, :miles_driven, :purpose, :vehicle_id

  #Associations
  belongs_to :vehicle
  
  #Validations
  validates_presence_of :date, :destination, :miles_driven, :purpose, :vehicle_id
end

app/controllers/mileage_segments_controller.rb
class MileageSegmentsController < ApplicationController
  # GET /mileage_segments
  # GET /mileage_segments.json
  def index
    @mileage_segments = MileageSegment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mileage_segments }
    end
  end

  # GET /mileage_segments/1
  # GET /mileage_segments/1.json
  def show
    @mileage_segment = MileageSegment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mileage_segment }
    end
  end

  # GET /mileage_segments/new
  # GET /mileage_segments/new.json
  def new
    @mileage_segment = MileageSegment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mileage_segment }
    end
  end

  # GET /mileage_segments/1/edit
  def edit
    @mileage_segment = MileageSegment.find(params[:id])
  end

  # POST /mileage_segments
  # POST /mileage_segments.json
  def create
    @mileage_segment = MileageSegment.new(params[:mileage_segment])

    respond_to do |format|
      if @mileage_segment.save
        format.html { redirect_to @mileage_segment, notice: 'Mileage segment was successfully created.' }
        format.json { render json: @mileage_segment, status: :created, location: @mileage_segment }
      else
        format.html { render action: "new" }
        format.json { render json: @mileage_segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mileage_segments/1
  # PUT /mileage_segments/1.json
  def update
    @mileage_segment = MileageSegment.find(params[:id])

    respond_to do |format|
      if @mileage_segment.update_attributes(params[:mileage_segment])
        format.html { redirect_to @mileage_segment, notice: 'Mileage segment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mileage_segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mileage_segments/1
  # DELETE /mileage_segments/1.json
  def destroy
    @mileage_segment = MileageSegment.find(params[:id])
    @mileage_segment.destroy

    respond_to do |format|
      format.html { redirect_to mileage_segments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mileage_segments_helper.rb
module MileageSegmentsHelper
end

app/views/mileage_segments/_form.html.erb
<%= simple_form_for(@mileage_segment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :vehicle_id, :collection => Vehicle.all, :label_method => :vehicle_model, :value_method => :id  %>
    <%= link_to 'Add Vehicle', new_vehicle_path %>
    <%= f.input :date %>
    <%= f.input :miles_driven %>
    <%= f.input :destination %>
    <%= f.input :purpose %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Add Segment" %>
  </div>
<% end %>

app/views/mileage_segments/edit.html.erb
<h1>Mileage Segments</h1>

<%= render 'form' %>

<%= link_to 'Show', @mileage_segment %> |
<%= link_to 'Back', mileage_segments_path %>

app/views/mileage_segments/index.html.erb
<h1>Mileage Segments</h1>

<table>
  <tr>
    <th>Vehicle</th>
    <th>Date</th>
    <th>Miles Driven</th>
    <th>Destination</th>
    <th>Purpose</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mileage_segments.each do |mileage_segment| %>
  <tr>
    <td><%= mileage_segment.vehicle.vehicle_model %></td>
    <td><%= mileage_segment.date %></td>
    <td><%= mileage_segment.miles_driven %></td>
    <td><%= mileage_segment.destination %></td>
    <td><%= mileage_segment.purpose %></td>
    <td><%= link_to 'Show', mileage_segment %></td>
    <td><%= link_to 'Edit', edit_mileage_segment_path(mileage_segment) %></td>
    <td><%= link_to 'Destroy', mileage_segment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Segment', new_mileage_segment_path %> | <%= link_to 'Vehicles', vehicles_path %>  | <%= link_to 'Add Vehicle', new_vehicle_path %>

app/views/mileage_segments/new.html.erb
<h1>Mileage Segments</h1>

<%= render 'form' %>

<%= link_to 'Back', mileage_segments_path %> 

app/views/mileage_segments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Vehicle:</b>
  <%= @mileage_segment.vehicle.vehicle_model %>
</p>

<p>
  <b>Date:</b>
  <%= @mileage_segment.date %>
</p>

<p>
  <b>Miles Driven:</b>
  <%= @mileage_segment.miles_driven %>
</p>

<p>
  <b>Destination:</b>
  <%= @mileage_segment.destination %>
</p>

<p>
  <b>Purpose:</b>
  <%= @mileage_segment.purpose %>
</p>


<%= link_to 'Edit', edit_mileage_segment_path(@mileage_segment) %> |
<%= link_to 'Back', mileage_segments_path %>