config/routes.rb
GeneralExpense::Application.routes.draw do
  resources :clients

  resources :mileage_segments

  resources :travel_expenses

  resources :travels

  resources :vehicle_expenses

  resources :vehicles

  resources :me_exps

  resources :gen_exps

  resources :expenses

   root :to => 'gen_exps#index'

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  attr_accessible :make, :vehicle_model, :reg_no, :vin, :year, :business_vehicle

  #Associations 
  has_many :vehicle_expenses
  has_many :mileage_segments

  #Validations
  validates_uniqueness_of :vin
  validates_presence_of :make, :vehicle_model, :reg_no, :vin, :year
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicles }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/new
  # GET /vehicles/new.json
  def new
    @vehicle = Vehicle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(params[:vehicle])

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render json: @vehicle, status: :created, location: @vehicle }
      else
        format.html { render action: "new" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicles/1
  # PUT /vehicles/1.json
  def update
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      if @vehicle.update_attributes(params[:vehicle])
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= simple_form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :make %>
    <%= f.input :vehicle_model %>
    <%= f.input :year %>
    <%= f.input :business_vehicle %>
    <%= f.input :vin %>
    <%= f.input :reg_no %>
  <div class="actions">
    <%= f.button :submit, "Add Vehicle" %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Vehicles</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Vehicles</h1>

<table>
  <tr>
    <th>Year</th>
    <th>Make</th>
    <th>Model</th>
    <th>Business Vehicle?</th>
    <th>Vin</th>
    <th>Reg no</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vehicles.each do |vehicle| %>
  <tr>
    <td><%= vehicle.year %></td>
    <td><%= vehicle.make %></td>
    <td><%= vehicle.vehicle_model %></td>
    <td><%= vehicle.business_vehicle ? 'Yes' : 'No' %></td>
    <td><%= vehicle.vin %></td>
    <td><%= vehicle.reg_no %></td>
    <td><%= link_to 'Show', vehicle %></td>
    <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
    <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Vehicle', new_vehicle_path %> | <%= link_to 'Vehicle Expenses', vehicle_expenses_path %> | <%= link_to 'Mileage Segments', mileage_segments_path %>

app/views/vehicles/new.html.erb
<h1>Vehicles</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <b>Year:</b>
  <%= @vehicle.year %>
</p>

<p>
  <b>Make:</b>
  <%= @vehicle.make %>
</p>

<p>
  <b>Model:</b>
  <%= @vehicle.vehicle_model %>
</p>

<p>
  <b>Business Vehicle?</b>
  <%= @vehicle.business_vehicle ? 'Yes' : 'No' %>
</p>

<p>
  <b>VIN:</b>
  <%= @vehicle.vin %>
</p>

<p>
  <b>Registration Number:</b>
  <%= @vehicle.reg_no %>
</p>


<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Vehicles', vehicles_path %> | <%= link_to 'New Expense', new_vehicle_expense_path %> | <%= link_to "New Segment", new_mileage_segment_path %>