config/routes.rb
GeneralExpense::Application.routes.draw do
  resources :clients

  resources :mileage_segments

  resources :travel_expenses

  resources :travels

  resources :vehicle_expenses

  resources :vehicles

  resources :me_exps

  resources :gen_exps

  resources :expenses

   root :to => 'gen_exps#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>General Expenses</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="container" style="padding-top:40px">

	<div class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
			<!--<%= link_to %>-->
			<div class="nav-collapse">
		
				<!--<ul class="nav">
					<li>
		              	<%= link_to "General Expenses", gen_exps_path %>
		          	</li>
		          	
		          	<li>
		            	<%= link_to "Travel Expenses", travel_expenses_path %>
		          	</li>
		          	
		          	<li>
		          		<%= link_to "Vehicle Expenses", vehicle_expenses_path %>
		          	</li>
		          	
		          	<li>
		          		<%= link_to "Mileage Segments", mileage_segments_path %>
		          	</li>
		          	
		          	<li>
		          		<%= link_to "Meals & Entertainment", me_exps_path %>
		          	</li>
		          	
		         </ul> -->
		         
		         <ul class="nav" style="float:left">
		         	<li>
		         		<%= link_to 'ExpenseHub', gen_exps_path %>
		         	</li>
		         	<li>
		         		<%= link_to 'Receipt Uploader', new_expense_path %>
		         	</li>
		         	<li>
		         		<%= link_to "I am a client", clients_path %>
		         	</li>
		         	<li>
		         		<%= link_to "I am a bookkeeper", "#{}" %>
		         	</li>
		         </ul>
			</div>
		</div>
	</div>
	</div>
<%= yield %>

</body>
</html>